Update bin scripts from jack hammer

diff --git a/bin/tfail b/bin/tfail
--- a/bin/tfail
+++ b/bin/tfail
@@ -1,11 +1,19 @@
 #!/bin/bash
 # List the failed tests
 
+d="$1"
+[ "$1" == "" ] && d=$pt
 
-cd $p/test
+cd $d
 {
-    for f in *.tst
+    
+    files=`ls $d/*.tst`
+    #echo "Tests: $files"
+    [ -z "$files" ] && echo "ERROR: no tests found $d" && exit 1
+
+    for f in $files
     do 
+        #echo "tdiff $f"
         [[ ! -z `tdiff $f` ]] && echo FAILED: ${f/.tst/}
     done
 } | tee fail
